from django.urls import path

from .views import (
    CabinetListCreateAPIView,
    CabinetRetrieveUpdateDestroyAPIView,
    DoctorListCreateAPIView,
    DoctorPatientsAnalyticsAPIView,
    DoctorPeriodReportAPIView,
    DoctorRetrieveUpdateDestroyAPIView,
    DoctorWithPatientsAPIView,
    DoctorsByWorkDateAPIView,
    MedicalCardListCreateAPIView,
    MedicalCardRetrieveUpdateDestroyAPIView,
    MedicalCardWithVisitsAPIView,
    OtolaryngologyPatientsAPIView,
    PaidPatientsAPIView,
    PatientListCreateAPIView,
    PatientRetrieveUpdateDestroyAPIView,
    PriceListListCreateAPIView,
    PriceListRetrieveUpdateDestroyAPIView,
    TreatmentSumsAPIView,
    VisitListCreateAPIView,
    VisitRetrieveUpdateDestroyAPIView,
    VisitsCountByDateAPIView,
    WorkScheduleListCreateAPIView,
    WorkScheduleRetrieveUpdateDestroyAPIView,
)

urlpatterns = [
    path("doctors/", DoctorListCreateAPIView.as_view()),
    path("doctors/<int:pk>/", DoctorRetrieveUpdateDestroyAPIView.as_view()),
    path("doctors/<int:pk>/patients/", DoctorWithPatientsAPIView.as_view()),
    path("patients/", PatientListCreateAPIView.as_view()),
    path("patients/<int:pk>/", PatientRetrieveUpdateDestroyAPIView.as_view()),
    path("medical-cards/", MedicalCardListCreateAPIView.as_view()),
    path("medical-cards/<int:pk>/", MedicalCardRetrieveUpdateDestroyAPIView.as_view()),
    path("medical-cards/<int:pk>/visits/", MedicalCardWithVisitsAPIView.as_view()),
    path("visits/", VisitListCreateAPIView.as_view()),
    path("visits/<int:pk>/", VisitRetrieveUpdateDestroyAPIView.as_view()),
    path("cabinets/", CabinetListCreateAPIView.as_view()),
    path("cabinets/<int:pk>/", CabinetRetrieveUpdateDestroyAPIView.as_view()),
    path("price-list/", PriceListListCreateAPIView.as_view()),
    path("price-list/<int:pk>/", PriceListRetrieveUpdateDestroyAPIView.as_view()),
    path("schedules/", WorkScheduleListCreateAPIView.as_view()),
    path("schedules/<int:pk>/", WorkScheduleRetrieveUpdateDestroyAPIView.as_view()),
    path("analytics/doctor/<int:doctor_id>/patients/", DoctorPatientsAnalyticsAPIView.as_view()),
    path("analytics/otolaryngology-patients/", OtolaryngologyPatientsAPIView.as_view()),
    path("analytics/doctors-by-date/", DoctorsByWorkDateAPIView.as_view()),
    path("analytics/visits-by-date/", VisitsCountByDateAPIView.as_view()),
    path("analytics/treatment-sums/", TreatmentSumsAPIView.as_view()),
    path("analytics/paid-patients/", PaidPatientsAPIView.as_view()),
    path("analytics/doctor-period-report/", DoctorPeriodReportAPIView.as_view()),
]
